runtime: python39  # or python38 if you're using Python 3.8

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto



entrypoint: python app.py


env_variables:
  FLASK_ENV: production
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://BenFuqua:2001053597Rex?@/CoralClientSeller?unix_socket=/cloudsql/corals4cheap:us-west1:coralclientsellerdb"

beta_settings:
  cloud_sql_instances: "corals4cheap:us-west1:coralclientsellerdb"
